title: Keydesign
email: hello@keydesign.com
description: >-
  Keydesign specializes in industrial design services, offering support from the initial concepts to the final design. Founded by George and Antonija Campbell in 2001, Keydesign has helped startups get to the next level (from humble beginnings to IPO) and worked with established companies to innovate and stay ahead of the competition.
url: "https://keydesign.com"
collections:
  blogs:
    output: true
    permalink: /blogs/:title/
  ideas:
    output: true
    permalink: /ideas/:title/
  pages:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /projects/:title/
idea_order:
  - sand_clock_teacup
  - milk_frother
  - color_me_healthy
  - samsung_mobile_design_competition
  - wine_glass_packaging
  - chocolate_3d_printing_pen
project_order:
  - jame_technology__morphing_iphone_case_stand
  - live_copper__smart_desk_woofer
  - five_stars__point_of_sale_display_gen3
  - live_copper__smart_desk_model_C
  - golden_trees__solar_lamp_flexible_post
  - stemp__wireless_thermometer
  - jame_technology__apple_tv_remote_case
  - optari__sol_tote
  - patchworks__wallet_case_iphone
  - natures_cooling_solutions__eco_thermostat
  - osmo__storage_case
  - hartmann__luggage
  - somnarus__sleep_apnea_monitor
  - five_stars__point_of_sale_display_gen1
  - five_stars__point_of_sale_display_gen2
  - neotop__formula_dispenser
  - golden_trees__flashlight_nightlight
  - golden_trees__outdoor_solar_lamp
  - hansnap__snap_ring
  - natures_cooling_solutions_eco_breeze
  - optari__backpack_handbag
  - cesium__rugged_edu_case
  - jame_technology__invisible_protection_case_iphone
  - biophilia_activangel__wireless_thermometer
  - zuslab__armor_shield_anti_shock_case_iphone
  - jame_technology__fashion_cases_samsung
  - puregear__iphone_case
  - jame_technology__fashion_cases_iphone
  - jame_technology__nintendo_switch_grip_case
  - jame_technology__car_mount
  - newgy__ball_catching_net
  - tilt_five__packaging_design
  - various_clients__trend_research
